### ISSUE TITLE
Unable to upgrate from 1.6.1 to 1.7.0

### ISSUE THREAD

**Issue by AuRoN89** [xchwarze/ckeditor-phpbb#4]
Hi, i have a phpbb board with CKEditor-phpbb version 1.6.1 and everything is working fine. When i try to update to version 1.7.0 there is an error 500 when users try to load a topic.

here the error:

[26-May-2024 14:25:23 UTC] PHP Fatal error:  Uncaught Twig\Error\LoaderError: Unable to find template "@dsr_ckeditor/js/ckeditor/adapters/jquery.js" (looked into: public_html/community/ext/dsr/ckeditor/styles/all/template, public_html/community/ext/dsr/ckeditor/styles/all/template) in "@dsr_ckeditor/event/overall_footer_after.html" at line 3. in public_html/community/vendor/twig/twig/src/Loader/FilesystemLoader.php:250
Stack trace:
#0 public_html/community/phpbb/template/twig/loader.php(135): Twig\Loader\FilesystemLoader->findTemplate('@dsr_ckeditor/j...', true)
#1 public_html/community/vendor/twig/twig/src/Loader/FilesystemLoader.php(150): phpbb\template\twig\loader->findTemplate('@dsr_ckeditor/j...')
#2 public_html/community/phpbb/template/twig/environment.php(328): Twig\Loader\FilesystemLoader->getCacheKey('@dsr_ckeditor/j...')
#3 public_html/community/cache/production/twig/14/14a80f471900bf32eecf97893bb54424b09feeb78af4978ea3ab98616081e6cb.php(60 in public_html/community/vendor/twig/twig/src/Loader/FilesystemLoader.php on line 250
[26-May-2024 14:25:26 UTC] PHP Fatal error:  Uncaught Twig\Error\LoaderError: Unable to find template "@dsr_ckeditor/js/ckeditor/adapters/jquery.js" (looked into: public_html/community/ext/dsr/ckeditor/styles/all/template, public_html/community/ext/dsr/ckeditor/styles/all/template) in "@dsr_ckeditor/event/overall_footer_after.html" at line 3. in public_html/community/vendor/twig/twig/src/Loader/FilesystemLoader.php:250
Stack trace:
#0 public_html/community/phpbb/template/twig/loader.php(135): Twig\Loader\FilesystemLoader->findTemplate('@dsr_ckeditor/j...', true)
#1 public_html/community/vendor/twig/twig/src/Loader/FilesystemLoader.php(150): phpbb\template\twig\loader->findTemplate('@dsr_ckeditor/j...')
#2 public_html/community/phpbb/template/twig/environment.php(328): Twig\Loader\FilesystemLoader->getCacheKey('@dsr_ckeditor/j...')
#3 public_html/community/cache/production/twig/14/14a80f471900bf32eecf97893bb54424b09feeb78af4978ea3ab98616081e6cb.php(60 in public_html/community/vendor/twig/twig/src/Loader/FilesystemLoader.php on line 250

**the folder adapters with the jquery.js file is MISSING**

Restoring the file from the previous version fix the error 500, but CKEditor it's not visible and these are the new errors:

![image](https://github.com/xchwarze/ckeditor-phpbb/assets/4964327/2162fb49-69ec-474e-8d5e-bdb8288db0d3)

**Comment by xchwarze** [comment]
CKEditor deleted those js from the build. When I can I check if they are necessary or not.
I want to believe they are not and just update the templates.

**Comment by xchwarze** [comment]
Reviewing the CKEditor 4 release notes I understand that they were deleted by mistake, so I made a new release using the files that were already versioned in this repo.
It should be fixed.

**Comment by AuRoN89** [comment]
Hi xchwarze, i just tried the new version but the issue still persists. The error 500 is not longer there, but CKEditor it's not visible, exactly the same issue that happened to me when i tried manually restore the removed files from previous version.

**Comment by xchwarze** [comment]
maybe it's completely broken that ckeditor release. It is the last one that the company makes for free so I would think that it is functional...
Could you check the javascript console and copy the errors here?

**Comment by AuRoN89** [comment]
the errors are the same as the ones posted before:

![image](https://github.com/xchwarze/ckeditor-phpbb/assets/4964327/72fcf09a-acbd-4676-b43d-984d231dc0a3)

**Comment by tig** [comment]
Same problem here.
